"""Initial migration

Revision ID: 7876525c546e
Revises: 
Create Date: 2025-12-30 06:20:11.919818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7876525c546e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('formats', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_conversions_created_success', ['created_at', 'success'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_error_code'), ['error_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversions_success'), ['success'], unique=False)
        batch_op.create_index('ix_conversions_visitor_created', ['visitor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('browser', sa.String(length=200), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_views_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_views_path'), ['path'], unique=False)
        batch_op.create_index('ix_page_views_path_created', ['path', 'created_at'], unique=False)
        batch_op.create_index('ix_page_views_visitor_created', ['visitor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_views_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_sessions_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_revoked'))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_expires_at'))

    op.drop_table('admin_sessions')
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_views_visitor_id'))
        batch_op.drop_index('ix_page_views_visitor_created')
        batch_op.drop_index('ix_page_views_path_created')
        batch_op.drop_index(batch_op.f('ix_page_views_path'))
        batch_op.drop_index(batch_op.f('ix_page_views_created_at'))

    op.drop_table('page_views')
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversions_visitor_id'))
        batch_op.drop_index('ix_conversions_visitor_created')
        batch_op.drop_index(batch_op.f('ix_conversions_success'))
        batch_op.drop_index(batch_op.f('ix_conversions_job_id'))
        batch_op.drop_index(batch_op.f('ix_conversions_error_code'))
        batch_op.drop_index('ix_conversions_created_success')
        batch_op.drop_index(batch_op.f('ix_conversions_created_at'))

    op.drop_table('conversions')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
